name: CI-Pipeline

# Controls when the workflow will run, when comment is created
on:
  issue_comment:
    types:
      - created
jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci-v2.yml@v1.18.2
    secrets: inherit
    with:
        craSCCv2: true
        craTarget: "examples/two-vpcs"
        craRuleIgnoreFile: "cra-tf-validate-ignore-rules.json"
        craEnvironmentVariables: "TF_VAR_transit_gateway_name=transit-gateway, TF_VAR_region=us-south"
